MD_MODEL: "md_v4.1.0.pb"
INPUT_DIR: "/images/"
MD_FILE: "md_out.json"
RECURSIVE: True
RELATIVE_FILENAMES: True
QUIET: True
THRESHOLD: 0.01
CHECKPOINT_FREQ: 100
CHECKPOINT_PATH: None
RESUME_CHECKPOINT: False
NCORES: 0
